version: '3'

services:

  broker:
    build: broker
    hostname: ${BROKERNAME}
    ports:
      - ${RABBITMQ_MANAGEMENT_PORT}:15672

  client:
    build: client
    ports:
      - ${JUPYTER_PORT}:${JUPYTER_PORT} 
    environment:
      - JUPYTER_PORT=${JUPYTER_PORT} 
      - BROKERNAME=${BROKERNAME}
      - TOPIC=${TOPIC}
      - MQTT_PORT=${MQTT_PORT}
    depends_on:
      - "consumer"

  consumer:
    build: consumer
    environment:
      - BROKERNAME=${BROKERNAME}
      - TOPIC=${TOPIC}
      - TERM=xterm
    depends_on:
      - "broker"
    restart: on-failure

networks: 
  default:
    driver: bridge